# Generated by Django 2.2.24 on 2023-05-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20230529_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='text',
            new_name='description',
        ),
    ]
